questions = [
    {"question": "What is the capital of Pakistan?", "options": ["Lahore", "Karachi", "Peshawar", "Islamabad"], "answer": "Islamabad"},
    {"question": "Who developed the theory of relativity?", "options": ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], "answer": "Albert Einstein"},
    {"question": "What is the largest ocean on Earth?", "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], "answer": "Pacific Ocean"},
    {"question": "Which planet is known as the Red Planet?", "options": ["Earth", "Venus", "Mars", "Jupiter"], "answer": "Mars"},
    {"question": "Who painted the Mona Lisa?", "options": ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"], "answer": "Leonardo da Vinci"},
    {"question": "What is the chemical symbol for gold?", "options": ["Ag", "Au", "Pb", "Fe"], "answer": "Au"},
    {"question": "What is the longest river in the world?", "options": ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], "answer": "Nile River"},
    {"question": "Which country is famous for the Great Wall?", "options": ["India", "China", "Japan", "Russia"], "answer": "China"},
    {"question": "How many continents are there on Earth?", "options": ["5", "6", "7", "8"], "answer": "7"},
    {"question": "Who wrote 'Hamlet'?", "options": ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], "answer": "William Shakespeare"},
    {"question": "What gas do plants absorb from the atmosphere?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "answer": "Carbon Dioxide"},
    {"question": "Which metal is the best conductor of electricity?", "options": ["Copper", "Silver", "Gold", "Aluminum"], "answer": "Silver"},
    {"question": "Who was the first person to walk on the moon?", "options": ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"], "answer": "Neil Armstrong"},
    {"question": "Which element is needed for bones to be strong?", "options": ["Iron", "Calcium", "Potassium", "Magnesium"], "answer": "Calcium"},
    {"question": "Which is the smallest planet in the solar system?", "options": ["Mars", "Venus", "Mercury", "Pluto"], "answer": "Mercury"},
    {"question": "What is the currency of Japan?", "options": ["Won", "Rupee", "Yen", "Dollar"], "answer": "Yen"},
    {"question": "Which bird is known for its ability to mimic sounds?", "options": ["Parrot", "Eagle", "Sparrow", "Owl"], "answer": "Parrot"},
    {"question": "Who discovered gravity?", "options": ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Thomas Edison"], "answer": "Isaac Newton"},
    {"question": "What is the chemical symbol for water?", "options": ["H2O", "CO2", "NaCl", "O2"], "answer": "H2O"},
    {"question": "Which is the largest desert in the world?", "options": ["Sahara", "Gobi", "Kalahari", "Antarctic"], "answer": "Antarctic"},
    {"question": "Who was the first President of the United States?", "options": ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], "answer": "George Washington"},
    {"question": "Which country is home to the kangaroo?", "options": ["India", "South Africa", "Australia", "Brazil"], "answer": "Australia"},
    {"question": "How many bones are there in an adult human body?", "options": ["206", "210", "215", "200"], "answer": "206"},
    {"question": "What is the speed of light in vacuum?", "options": ["300,000 km/s", "150,000 km/s", "1,000,000 km/s", "500,000 km/s"], "answer": "300,000 km/s"},
    {"question": "Which programming language is used for web development?", "options": ["Python", "Java", "JavaScript", "C++"], "answer": "JavaScript"},
    {"question": "What is the boiling point of water at sea level?", "options": ["90°C", "100°C", "120°C", "80°C"], "answer": "100°C"},
    {"question": "What is the capital of France?", "options": ["Madrid", "Rome", "Berlin", "Paris"], "answer": "Paris"},
    {"question": "Which is the deepest ocean?", "options": ["Indian Ocean", "Atlantic Ocean", "Arctic Ocean", "Pacific Ocean"], "answer": "Pacific Ocean"},
    {"question": "What is the main gas found in Earth's atmosphere?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": "Nitrogen"},
    {"question": "Which part of the plant conducts photosynthesis?", "options": ["Root", "Stem", "Leaf", "Flower"], "answer": "Leaf"},
    {"question": "Which is the hardest natural substance on Earth?", "options": ["Gold", "Iron", "Diamond", "Platinum"], "answer": "Diamond"},
    {"question": "What is the first pillar of Islam?", "options": ["Salah", "Zakat", "Shahada", "Hajj"], "answer": "Shahada"},
    {"question": "How many times a day is a Muslim required to pray?", "options": ["3", "5", "7", "10"], "answer": "5"},
    {"question": "What is the holy book of Islam?", "options": ["Bible", "Torah", "Quran", "Vedas"], "answer": "Quran"},
    {"question": "Who is the last prophet in Islam?", "options": ["Isa (AS)", "Musa (AS)", "Ibrahim (AS)", "Muhammad (PBUH)"], "answer": "Muhammad (PBUH)"},
    {"question": "Which angel delivered Allah's revelations to the prophets?", "options": ["Jibrael (AS)", "Mikail (AS)", "Israfil (AS)", "Azrael (AS)"], "answer": "Jibrael (AS)"},
    {"question": "What is the Islamic place of worship called?", "options": ["Temple", "Mosque", "Synagogue", "Church"], "answer": "Mosque"},
    {"question": "In which month do Muslims fast from dawn to sunset?", "options": ["Muharram", "Ramadan", "Shawwal", "Dhul-Hijjah"], "answer": "Ramadan"},
    {"question": "Which city is considered the holiest in Islam?", "options": ["Medina", "Jerusalem", "Mecca", "Baghdad"], "answer": "Mecca"},
    {"question": "What is the term for charity in Islam?", "options": ["Salah", "Hajj", "Zakat", "Tawaf"], "answer": "Zakat"},
    {"question": "What is the meaning of 'Islam'?", "options": ["Peace", "Submission", "Faith", "Prayer"], "answer": "Submission"},
    {"question": "Who was the first caliph after Prophet Muhammad (PBUH)?", "options": ["Umar ibn Khattab", "Ali ibn Abi Talib", "Abu Bakr", "Uthman ibn Affan"], "answer": "Abu Bakr"},
    {"question": "How many chapters (Surahs) are there in the Quran?", "options": ["100", "114", "120", "99"], "answer": "114"},
    {"question": "Which surah is known as the 'Mother of the Quran'?", "options": ["Surah Al-Baqarah", "Surah Al-Ikhlas", "Surah Al-Fatiha", "Surah Al-Kahf"], "answer": "Surah Al-Fatiha"},
    {"question": "What is the night called when the Quran was first revealed?", "options": ["Shab-e-Miraj", "Laylatul Qadr", "Eid night", "Shab-e-Baraat"], "answer": "Laylatul Qadr"},
    {"question": "What is the Arabic term for pilgrimage to Mecca?", "options": ["Umrah", "Zakat", "Hajj", "Salah"], "answer": "Hajj"},
    {"question": "Who built the Kaaba along with his son Ismail (AS)?", "options": ["Musa (AS)", "Dawood (AS)", "Ibrahim (AS)", "Suleiman (AS)"], "answer": "Ibrahim (AS)"},
    {"question": "How many articles of faith (Iman) are there in Islam?", "options": ["3", "5", "6", "10"], "answer": "6"},
    {"question": "Which prophet is mentioned most in the Quran?", "options": ["Musa (AS)", "Isa (AS)", "Ibrahim (AS)", "Nuh (AS)"], "answer": "Musa (AS)"},
    {"question": "Which Islamic month marks the beginning of the Islamic calendar?", "options": ["Ramadan", "Rabi-ul-Awwal", "Muharram", "Shawwal"], "answer": "Muharram"},
    {"question": "What does 'Haram' mean in Islam?", "options": ["Blessed", "Forbidden", "Permissible", "Mandatory"], "answer": "Forbidden"},
    {"question": "Which companion compiled the Quran into a book form?", "options": ["Ali ibn Abi Talib", "Abu Bakr", "Umar ibn Khattab", "Uthman ibn Affan"], "answer": "Uthman ibn Affan"},
    {"question": "Which animal is mentioned the most in the Quran?", "options": ["Camel", "Horse", "Cow", "Elephant"], "answer": "Cow"},
    {"question": "Who was the first woman to embrace Islam?", "options": ["Aisha (RA)", "Hafsa (RA)", "Khadija (RA)", "Fatima (RA)"], "answer": "Khadija (RA)"},
    {"question": "What is the name of the well that appeared for Ismail (AS) and Hajar (AS) in Mecca?", "options": ["Zamzam", "Safa", "Marwa", "Kawthar"], "answer": "Zamzam"},
    {"question": "What is the name of the Friday prayer in Islam?", "options": ["Fajr", "Dhuhr", "Asr", "Jummah"], "answer": "Jummah"},
    {"question": "How many prophets are mentioned by name in the Quran?", "options": ["10", "25", "50", "124,000"], "answer": "25"},
    {"question": "Which prophet is associated with building the Ark?", "options": ["Ibrahim (AS)", "Musa (AS)", "Nuh (AS)", "Yunus (AS)"], "answer": "Nuh (AS)"},
    {"question": "What is the longest Surah in the Quran?", "options": ["Surah Al-Fatiha", "Surah Al-Ikhlas", "Surah Al-Baqarah", "Surah Yaseen"], "answer": "Surah Al-Baqarah"},
    {"question": "What was the first revelation given to Prophet Muhammad (PBUH)?", "options": ["Pray", "Believe", "Read", "Fast"], "answer": "Read"},
    {"question": "How many Rakats are in Isha prayer?", "options": ["2", "4", "5", "17"], "answer": "17"},
    {"question": "Which angel is responsible for taking souls?", "options": ["Jibrael (AS)", "Mikail (AS)", "Israfil (AS)", "Azrael (AS)"], "answer": "Azrael (AS)"},
    {"question": "Which companion is known as 'The Sword of Allah'?", "options": ["Abu Bakr (RA)", "Umar ibn Khattab (RA)", "Ali ibn Abi Talib (RA)", "Khalid bin Walid (RA)"], "answer": "Khalid bin Walid (RA)"},
    {"question": "What is the name of Prophet Muhammad's (PBUH) father?", "options": ["Abu Talib", "Abdullah", "Ibrahim", "Hashim"], "answer": "Abdullah"},
    {"question": "What is the reward for fasting during Ramadan?", "options": ["Wealth", "Forgiveness of sins", "Long life", "Health"], "answer": "Forgiveness of sins"},
    {"question": "Which prophet was swallowed by a whale?", "options": ["Musa (AS)", "Isa (AS)", "Yunus (AS)", "Nuh (AS)"], "answer": "Yunus (AS)"},
    {"question": "What is the first Surah of the Quran?", "options": ["Surah Al-Baqarah", "Surah Al-Ikhlas", "Surah Al-Fatiha", "Surah Al-Nas"], "answer": "Surah Al-Fatiha"},
    {"question": "Which event is associated with the night journey and ascension of Prophet Muhammad (PBUH)?", "options": ["Hijrah", "Battle of Badr", "Isra and Miraj", "Conquest of Mecca"], "answer": "Isra and Miraj"},
    {"question": "When did Pakistan gain independence?", "options": ["14th August 1947", "15th August 1947", "23rd March 1940", "25th December 1947"], "answer": "14th August 1947"},
    {"question": "Who was the first Governor-General of Pakistan?", "options": ["Liaquat Ali Khan", "Allama Iqbal", "Quaid-e-Azam Muhammad Ali Jinnah", "Ayub Khan"], "answer": "Quaid-e-Azam Muhammad Ali Jinnah"},
    {"question": "What is the national language of Pakistan?", "options": ["Sindhi", "Punjabi", "Urdu", "Pashto"], "answer": "Urdu"},
    {"question": "Which city is the capital of Pakistan?", "options": ["Lahore", "Karachi", "Islamabad", "Peshawar"], "answer": "Islamabad"},
    {"question": "What is the national flower of Pakistan?", "options": ["Jasmine", "Rose", "Lily", "Tulip"], "answer": "Jasmine"},
    {"question": "What is the national sport of Pakistan?", "options": ["Cricket", "Hockey", "Football", "Squash"], "answer": "Hockey"},
    {"question": "Which currency is used in Pakistan?", "options": ["Rupee", "Dollar", "Taka", "Dinar"], "answer": "Rupee"},
    {"question": "What is the name of Pakistan’s national poet?", "options": ["Faiz Ahmed Faiz", "Mirza Ghalib", "Allama Iqbal", "Ahmed Faraz"], "answer": "Allama Iqbal"},
    {"question": "Which is the largest province of Pakistan by area?", "options": ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan"], "answer": "Balochistan"},
    {"question": "Which dam is the largest in Pakistan?", "options": ["Mangla Dam", "Tarbela Dam", "Warsak Dam", "Hub Dam"], "answer": "Tarbela Dam"},
    {"question": "Who was the first Prime Minister of Pakistan?", "options": ["Quaid-e-Azam", "Zulfikar Ali Bhutto", "Liaquat Ali Khan", "Benazir Bhutto"], "answer": "Liaquat Ali Khan"},
    {"question": "Which year did Pakistan become a nuclear power?", "options": ["1998", "1990", "2001", "1974"], "answer": "1998"},
    {"question": "Where is Minar-e-Pakistan located?", "options": ["Karachi", "Islamabad", "Peshawar", "Lahore"], "answer": "Lahore"},
    {"question": "Which is the highest mountain in Pakistan?", "options": ["K2", "Nanga Parbat", "Rakaposhi", "Broad Peak"], "answer": "K2"},
    {"question": "What does the white portion of the Pakistan flag represent?", "options": ["Peace", "Muslims", "Minorities", "Progress"], "answer": "Minorities"},
    {"question": "Who designed the national flag of Pakistan?", "options": ["Allama Iqbal", "Liaquat Ali Khan", "Ameer-ud-Din Kidwai", "Quaid-e-Azam"], "answer": "Ameer-ud-Din Kidwai"},
    {"question": "Which is the longest river in Pakistan?", "options": ["Ravi", "Chenab", "Jhelum", "Indus"], "answer": "Indus"},
    {"question": "Which city is known as the 'City of Lights'?", "options": ["Lahore", "Peshawar", "Karachi", "Islamabad"], "answer": "Karachi"},
    {"question": "What is the name of Pakistan's national airline?", "options": ["Air Blue", "Serene Air", "Pakistan International Airlines (PIA)", "Shaheen Air"], "answer": "Pakistan International Airlines (PIA)"},
    {"question": "Which movement led to the creation of Pakistan?", "options": ["Khilafat Movement", "Pakistan Movement", "Civil Disobedience Movement", "Quit India Movement"], "answer": "Pakistan Movement"},
    {"question": "Which city is famous for producing sports goods?", "options": ["Lahore", "Sialkot", "Faisalabad", "Gujranwala"], "answer": "Sialkot"},
    {"question": "What is the name of Pakistan’s national anthem?", "options": ["Sohni Dharti", "Dil Dil Pakistan", "Qaumi Tarana", "Pak Sarzameen"], "answer": "Qaumi Tarana"},
    {"question": "Who wrote the lyrics of the national anthem?", "options": ["Allama Iqbal", "Hafeez Jalandhari", "Faiz Ahmed Faiz", "Ahmed Faraz"], "answer": "Hafeez Jalandhari"},
    {"question": "Which city is known as the 'Heart of Pakistan'?", "options": ["Lahore", "Karachi", "Peshawar", "Quetta"], "answer": "Lahore"},
    {"question": "Where is Quaid-e-Azam Muhammad Ali Jinnah buried?", "options": ["Islamabad", "Lahore", "Karachi", "Rawalpindi"], "answer": "Karachi"},
    {"question": "What is the total number of districts in Pakistan?", "options": ["100", "120", "154", "160"], "answer": "154"},
    {"question": "Which sea borders Pakistan?", "options": ["Arabian Sea", "Caspian Sea", "Red Sea", "Bay of Bengal"], "answer": "Arabian Sea"},
    {"question": "Which neighboring country shares the longest border with Pakistan?", "options": ["China", "Afghanistan", "India", "Iran"], "answer": "India"},
    {"question": "Who was the first female Prime Minister of Pakistan?", "options": ["Fatima Jinnah", "Benazir Bhutto", "Maryam Nawaz", "Hina Rabbani Khar"], "answer": "Benazir Bhutto"},
    {"question": "What is the highest civilian award in Pakistan?", "options": ["Nishan-e-Haider", "Tamgha-e-Imtiaz", "Sitara-e-Pakistan", "Nishan-e-Pakistan"], "answer": "Nishan-e-Pakistan"},
    {"question": "Which city is called the 'Manchester of Pakistan'?", "options": ["Lahore", "Faisalabad", "Karachi", "Multan"], "answer": "Faisalabad"},
    {"question": "Which desert is located in Pakistan?", "options": ["Sahara", "Gobi", "Thar", "Karakum"], "answer": "Thar"},
    {"question": "Which province is known as the land of five rivers?", "options": ["Sindh", "Punjab", "Balochistan", "Khyber Pakhtunkhwa"], "answer": "Punjab"},
    {"question": "What is the official residence of the President of Pakistan?", "options": ["Parliament House", "Governor House", "Prime Minister House", "Aiwan-e-Sadr"], "answer": "Aiwan-e-Sadr"},
    {"question": "Who was the first Chief Justice of Pakistan?", "options": ["Justice Cornelius", "Justice Mian Abdul Rashid", "Justice Iftikhar Chaudhry", "Justice Saqib Nisar"], "answer": "Justice Mian Abdul Rashid"},
    {"question": "Which Pakistani scientist won the Nobel Prize in Physics?", "options": ["Dr. Abdul Qadeer Khan", "Dr. Abdus Salam", "Dr. Samar Mubarakmand", "Dr. Atta-ur-Rahman"], "answer": "Dr. Abdus Salam"},
    {"question": "Which is the second-largest city in Pakistan?", "options": ["Karachi", "Islamabad", "Lahore", "Peshawar"], "answer": "Lahore"},
    {"question": "Who was known as 'Baba-e-Qaum'?", "options": ["Liaquat Ali Khan", "Allama Iqbal", "Quaid-e-Azam", "Sir Syed Ahmed Khan"], "answer": "Quaid-e-Azam"},
    {"question": "What is the largest ocean on Earth?", "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], "answer": "Pacific Ocean"},
    {"question": "Which sea is the saltiest in the world?", "options": ["Dead Sea", "Mediterranean Sea", "Red Sea", "Black Sea"], "answer": "Dead Sea"},
    {"question": "Which is the deepest part of the ocean?", "options": ["Mariana Trench", "Java Trench", "Puerto Rico Trench", "Tonga Trench"], "answer": "Mariana Trench"},
    {"question": "Which ocean is the smallest?", "options": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Southern Ocean"], "answer": "Arctic Ocean"},
    {"question": "What percentage of the Earth's surface is covered by oceans?", "options": ["50%", "60%", "70%", "80%"], "answer": "70%"},
    {"question": "What is the longest river that flows into the sea?", "options": ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], "answer": "Amazon River"},
    {"question": "What is the world's largest coral reef system?", "options": ["Great Barrier Reef", "Belize Barrier Reef", "Red Sea Coral Reef", "New Caledonian Barrier Reef"], "answer": "Great Barrier Reef"},
    {"question": "Which sea is between Europe and Africa?", "options": ["Red Sea", "Baltic Sea", "Mediterranean Sea", "Caribbean Sea"], "answer": "Mediterranean Sea"},
    {"question": "Which ocean is home to the Bermuda Triangle?", "options": ["Pacific Ocean", "Indian Ocean", "Atlantic Ocean", "Southern Ocean"], "answer": "Atlantic Ocean"},
    {"question": "Which ocean surrounds Antarctica?", "options": ["Pacific Ocean", "Indian Ocean", "Arctic Ocean", "Southern Ocean"], "answer": "Southern Ocean"},
    {"question": "Which sea is located between Saudi Arabia and Africa?", "options": ["Caspian Sea", "Black Sea", "Red Sea", "Arabian Sea"], "answer": "Red Sea"},
    {"question": "What is the world's largest inland body of water?", "options": ["Caspian Sea", "Black Sea", "Aral Sea", "Dead Sea"], "answer": "Caspian Sea"},
    {"question": "What is the name of the largest sea mammal?", "options": ["Dolphin", "Orca", "Blue Whale", "Humpback Whale"], "answer": "Blue Whale"},
    {"question": "What is the term for an underwater mountain range?", "options": ["Oceanic Ridge", "Seamount", "Trench", "Plateau"], "answer": "Oceanic Ridge"},
    {"question": "What causes ocean tides?", "options": ["Sun's gravity", "Earth's rotation", "Wind", "Moon's gravity"], "answer": "Moon's gravity"},
    {"question": "What is the name of the current that flows along the East Coast of the US?", "options": ["California Current", "Gulf Stream", "Kuroshio Current", "Antarctic Circumpolar Current"], "answer": "Gulf Stream"},
    {"question": "Which ocean is known for having the roughest waters?", "options": ["Pacific Ocean", "Atlantic Ocean", "Southern Ocean", "Indian Ocean"], "answer": "Southern Ocean"},
    {"question": "Which sea separates the United Kingdom from Norway?", "options": ["Baltic Sea", "North Sea", "Irish Sea", "Norwegian Sea"], "answer": "North Sea"},
    {"question": "Which sea is known as the 'Sea of Tranquility'?", "options": ["Mediterranean Sea", "Baltic Sea", "Arabian Sea", "It’s on the Moon"], "answer": "It’s on the Moon"},
    {"question": "Which sea is the warmest on Earth?", "options": ["Red Sea", "Caribbean Sea", "Mediterranean Sea", "Arabian Sea"], "answer": "Red Sea"},
    {"question": "Which ocean has the most islands?", "options": ["Indian Ocean", "Atlantic Ocean", "Pacific Ocean", "Southern Ocean"], "answer": "Pacific Ocean"},
    {"question": "What is the name of a giant wave caused by an undersea earthquake?", "options": ["Typhoon", "Hurricane", "Tsunami", "Monsoon"], "answer": "Tsunami"},
    {"question": "Which ocean is the warmest?", "options": ["Pacific Ocean", "Indian Ocean", "Atlantic Ocean", "Arctic Ocean"], "answer": "Indian Ocean"},
    {"question": "Which is the largest island in the world?", "options": ["Madagascar", "Greenland", "Borneo", "Australia"], "answer": "Greenland"},
    {"question": "What is the process of seawater turning into freshwater called?", "options": ["Distillation", "Desalination", "Evaporation", "Condensation"], "answer": "Desalination"},
    {"question": "Which oceanic region is known for mysterious disappearances?", "options": ["Gulf of Mexico", "Bermuda Triangle", "Caribbean Sea", "Indian Ocean"], "answer": "Bermuda Triangle"},
    {"question": "Which ocean is located between Africa, Asia, Australia, and Antarctica?", "options": ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean", "Arctic Ocean"], "answer": "Indian Ocean"},
    {"question": "What is the term for small organisms that drift in the ocean?", "options": ["Phytoplankton", "Zooplankton", "Plankton", "Algae"], "answer": "Plankton"},
    {"question": "What is the name of the deepest point in the Atlantic Ocean?", "options": ["Java Trench", "Mariana Trench", "Puerto Rico Trench", "South Sandwich Trench"], "answer": "Puerto Rico Trench"},
    {"question": "Which is the world's longest coral reef?", "options": ["Red Sea Reef", "New Caledonian Barrier Reef", "Great Barrier Reef", "Belize Barrier Reef"], "answer": "Great Barrier Reef"},
    {"question": "What type of rock forms coral reefs?", "options": ["Limestone", "Basalt", "Granite", "Sandstone"], "answer": "Limestone"},
    {"question": "Which ocean current is responsible for warm waters along the western coast of Europe?", "options": ["California Current", "Kuroshio Current", "Gulf Stream", "Labrador Current"], "answer": "Gulf Stream"},
    {"question": "What is the deepest lake in the world?", "options": ["Lake Baikal", "Lake Superior", "Caspian Sea", "Lake Victoria"], "answer": "Lake Baikal"},
    {"question": "What is the name of the largest known underwater volcano?", "options": ["Tamu Massif", "Krakatoa", "Mauna Loa", "Mount St. Helens"], "answer": "Tamu Massif"},
    {"question": "What is the process of ocean water turning into vapor called?", "options": ["Evaporation", "Condensation", "Precipitation", "Transpiration"], "answer": "Evaporation"},
    {"question": "Which sea is connected to the Atlantic Ocean via the Suez Canal?", "options": ["Red Sea", "Black Sea", "Baltic Sea", "Arabian Sea"], "answer": "Red Sea"},
    {"question": "What is the term for the movement of water caused by wind?", "options": ["Tide", "Wave", "Current", "Gyre"], "answer": "Wave"},
    {"question": "Which ocean current keeps Europe warmer than it would otherwise be?", "options": ["Labrador Current", "Benguela Current", "Gulf Stream", "California Current"], "answer": "Gulf Stream"},
    {"question": "What is the deepest fish ever discovered?", "options": ["Blobfish", "Mariana Snailfish", "Anglerfish", "Viperfish"], "answer": "Mariana Snailfish"},
    {"question": "Which sea is bordered by Jordan and Israel?", "options": ["Red Sea", "Black Sea", "Dead Sea", "Mediterranean Sea"], "answer": "Dead Sea"}

]
